### PR TITLE
Use different algorithms depending on the ssh version

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Fixes GH-162

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
PR to ssh-baseline follows..(and is the reason for WIP)

**Comment by artem-sidorenko** [comment]
Currently this feature is server only (basically the same implementation like with privilege_separation). There is an option `HostKeyAlgorithms` which is valid for server and client, however this option is present on the server starting from something like openssh 6.7 (I do not know the exact version). So a proper server&client implementation would require a bit more changes in order to handle this.

Below an overview over different ssh versions and supported things (key stuff is mostly based on the @atomic111 [evaluation](https://github.com/dev-sec/ssh-baseline/pull/76#issuecomment-273044970)):

| | ubuntu 12.04 | ubuntu 14.04 | ubuntu 16.04 | centos 6.8 | centos 7.3 |
| - | ----------------  | ----------------- | ---------------- | -------------- | ------------- |
ssh version | 5.9 | 6.6 | 7.2 | 5.3 | 6.6 |
`ssh -Q key` support | | x | x | | x |
`HostKeyAlgorithms`/server support | | x | x | | |
dsa key | x | x | x | x | |
rsa key | x | x | x | x | x |
ecdsa key | | x | x | | x |
ed25519 key | | x | x | | x |


| | debian 7.11 | debian 8.6 | fedora 24 | fedora 25 | opensuse leap 42.1 | opensuse 13.2 |
| - | ------------  | -------------- | ------------ | ------------ | ------------------------- | ------------------- |
ssh version | 6.0 | 6.7 | 7.2 | 7.3 | 6.6 | 6.6 |
ssh version | | | | | | |
`ssh -Q key` support | | x | x | x | x | x |
`HostKeyAlgorithms`/server support | | | x | x | ? | ? |
dsa key | x | x | | | x | x |
rsa key | x | x | x | x | x | x |
ecdsa key | x | x | x | x | x | x |
ed25519 key | | x | x | x | x | x |

**Comment by artem-sidorenko** [comment]
and here is the PR with tests: https://github.com/dev-sec/ssh-baseline/pull/79

**Comment by artem-sidorenko** [comment]
The tests for failing opensuse 42.1 are in PR https://github.com/dev-sec/ssh-baseline/pull/84

**Comment by atomic111** [comment]
@artem-sidorenko thank you for the great work. now we can tag the version to 2.0.0. awesome

**Pull request merged**
