### PR TITLE
Add max_startup parameter

### PR DESCRIPTION
**Pull request by emmanuelCarre**
Hi,

Add parameter to allow to configure  `MaxStartups`.

Thx for work done into this cookbook.

### CODE REVIEW

**Comment by emmanuelCarre** [comment]
Hi,

We really need this change. There is anything I can do to help to merge this MR?

**Comment by emmanuelCarre** [comment]
Hi @artem-sidorenko (I ping you because you was mainly active maintainer few month ago), 

This project is still active? I follow that https://github.com/dev-sec/chef-ssh-hardening/blob/master/CONTRIBUTING.md#git-and-github; should I do something else more?

**Comment by artem-sidorenko** [comment]
@emmanuelCarre sorry for a delay, due covid related things(lockdowns, missing childcare etc), I'm currently offline with my opensource topics. MR looks good to me, however travis is red. I'll try to have a look in the next days/weeks.

**Comment by emmanuelCarre** [comment]
Hello,

No problem, I was worry about this project is abandoned. Stay safe and thank you for you time :)

**Comment by bdwyertech** [comment]
LGTM to bring in-line with https://github.com/dev-sec/ssh-baseline/pull/186

@chris-rock @artem-sidorenko

**Comment by emmanuelCarre** [comment]
Hi, 

@bazbremner, thank you for your feedback. I amend my commit.

**Comment by infertux** [comment]
LGTM. Any chance to get this merged in @artem-sidorenko? Thank you.

**Comment by emmanuelCarre** [comment]
I create this PR 2 years ago and there is no activity since January 2020. I close this PR and archive the fork; the change is still available here: https://github.com/dev-sec/chef-ssh-hardening/compare/master...emmanuelCarre:chef-ssh-hardening:add-max-startups.

I hope you are fine @artem-sidorenko.

Regards,

**Pull request closed without merging**
