### PR TITLE
Support for OpenSuse Leap, new enterprise distro of SUSE

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Its basically the open downstream built of SLE: http://www.cio.com/article/3003168/linux/7-things-you-should-know-about-opensuse-leap.html

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
Hm, suse testing is not included in the travis, so this issue was not catched. I will add it

**Comment by artem-sidorenko** [comment]
@chris-rock any idea about the timeout on suse testing on travis? I can not reproduce it locally :(

**Comment by chris-rock** [comment]
@artem-sidorenko Maybe we've an issue with the ssh config and suse does not let us in after hardening?

**Comment by atomic111** [comment]
@artem-sidorenko i restarted the travis job and it was working, but we got 3 inspec failures now.

**Comment by atomic111** [comment]
@artem-sidorenko i restarted travis and it was working, but i get now 3 inspec failures

https://travis-ci.org/dev-sec/chef-ssh-hardening/jobs/170690452

**Comment by artem-sidorenko** [comment]
@atomic111 thx, I see.

I'll have a look in the next days

**Comment by chris-rock** [comment]
Looks like file permissions for `/etc/ssh/ssh_config`, `/etc/ssh` and `/etc/ssh/sshd_config` are not properly configured.

**Comment by chris-rock** [comment]
This looks like a bug in inspec in combination with SUSE. https://github.com/chef/inspec/blob/master/lib/resources/file.rb#L142-L143

**Comment by chris-rock** [comment]
related to https://github.com/chef/inspec/issues/1264

**Comment by chris-rock** [comment]
Thanks @artem-sidorenko for adding opensuse leap to our integration test

**Comment by artem-sidorenko** [comment]
@chris-rock @atomic111 just make something, fail to reproduce the issue, do not have time for further investigation - the problem gets resolved by itself (or other people), thats cool :D

**Pull request merged**
