### PR TITLE
Removal of deprecated authorized_keys handling

### LINKED ISSUE #16: SSH rootkey configuration is too open
ssh keys for root are supported in the manner that fnichol/chef-user works. However, it has a bug: it pulls in users that aren't active.

We have a choice to make for 1.0 release: Either support ssh root keys fully, with the active users configuration of chef-user, or remove this support entirely.

Adding rootkey configuration in this manner is a 2year-old workaround to configure a server with keys for user root. We have to decide if this is still in scope of hardening. Feedback welcome.

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Resolves #16

### CODE REVIEW

**Comment by atomic111** [comment]
@artem-sidorenko thank you for the work. can you add a short hint for the users, how to handle the ssh keys.

**Comment by atomic111** [comment]
@artem-sidorenko thanks for cleaning this. May be you should add a hint in the README.md for the users. how to handle the ssh-key deployment. What do you think?

**Comment by artem-sidorenko** [comment]
@atomic111 I added a short notice that user/key handling are out-of-scope. I do not want to recommend any solution for user/key management, as it completely depends on the environment and particular needs (e.g. some manage keys/users via chef/puppet, in other setups you will see LDAP or IPA or even AD)

**Comment by artem-sidorenko** [comment]
@atomic111 and the deprecation notice was > 2 years old. In case somebody used it in the past - there was enough time to thing about alternatives :-)

**Comment by atomic111** [comment]
great, thank you

**Pull request merged**
