### PR TITLE
Bugfix: sshd listens on IPv6 interface if enabled

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Fixes GH-140

### CODE REVIEW

**Comment by atomic111** [comment]
@artem-sidorenko can you add a list in the README.md for attribute-precedence. I think, it is easier for the user to find out the attributes he can manipulate.

**Comment by chris-rock** [comment]
@artem-sidorenko Great addition. Could you rebase this to latest master?

**Comment by artem-sidorenko** [comment]
@chris-rock done
@atomic111 generally the user should use higher precedence level anyway. However sometimes you can find the attribute overriding on the same precedence level and the execution order. This won't work here and I just wanted to make it explicitly visible. I think its not cool to list/maintain a dedicated attribute list in the README. I've updated the notice in order to make the message more clear (hopefully)

**Comment by artem-sidorenko** [comment]
@chris-rock now it should be fixed

**Comment by artem-sidorenko** [comment]
@atomic111 @chris-rock guys, maybe you to stop "thank you for this and that" in my direction in each issue/PR?:-) Its cool for new contributors, by for me its getting annoying somehow :-) it makes an impression of something like a rule to write "thank you" in each PR

**Comment by chris-rock** [comment]
@artem-sidorenko Roger that. From now on, I'll give you harsh feedback only. :-)

**Comment by artem-sidorenko** [comment]
@chris-rock it does not have to be harsh, neutral feedback is fair enough:)

**Comment by chris-rock** [comment]
Haha, just kidding @artem-sidorenko

**Comment by atomic111** [comment]
@artem-sidorenko thank you for your great work. you pushed a lot of improvements.

**Comment by artem-sidorenko** [comment]
lol :+1:

**Comment by chris-rock** [comment]
@artem-sidorenko Are you going to rebase, so that we can merge this PR?

**Comment by artem-sidorenko** [comment]
@chris-rock done, please have a look

**Comment by chris-rock** [comment]
Looks all good @artem-sidorenko

**Pull request merged**
