### PR TITLE
Allow to configure ChallengeResponseAuthentication

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Closes https://github.com/dev-sec/chef-ssh-hardening/issues/125

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
@acucu can you please have a look, is this what you expect?

**Comment by acucu** [comment]
Yes, that's what I expect. Thank you very much!

**Comment by artem-sidorenko** [comment]
@atomic111 @chris-rock any remarks?

**Comment by atomic111** [comment]
@artem-sidorenko thank you for fixing #125

**Pull request merged**
